import { Category, Difficulty } from '../models/Exercise';
import { slugify } from '../utils/helpers';

export interface SeedExercise {
  name: string;
  muscleGroup: { primary: string; secondary: string[] };
  category: Category;
  difficulty: Difficulty;
  description: string;
  instructions: string[];
  tips: string[];
  equipment: string[];
  caloriesPerMinute: number;
}

const ex = (e: SeedExercise) => e;

export const seedExercises: SeedExercise[] = [
  // ────────── CHEST ──────────
  ex({
    name: 'Barbell Bench Press',
    muscleGroup: { primary: 'chest', secondary: ['triceps', 'shoulders'] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'The king of upper body pressing movements.',
    instructions: [
      'Lie flat on a bench with feet planted on the floor.',
      'Grip the bar slightly wider than shoulder width.',
      'Unrack and lower the bar to mid-chest under control.',
      'Press the bar up until elbows lock out.',
      'Keep shoulder blades retracted and pinned to the bench.',
    ],
    tips: ['Keep wrists stacked over elbows', 'Drive through your feet', 'Pause briefly at the chest'],
    equipment: ['barbell', 'bench', 'rack'],
    caloriesPerMinute: 7,
  }),
  ex({
    name: 'Incline Dumbbell Press',
    muscleGroup: { primary: 'chest', secondary: ['shoulders', 'triceps'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Targets the upper chest with a friendlier range of motion.',
    instructions: [
      'Set the bench to a 30-45° incline.',
      'Hold dumbbells at shoulder level, palms forward.',
      'Press up and slightly inward until arms lock out.',
      'Lower with control to chest level.',
    ],
    tips: ['Steeper angles shift work to shoulders', 'Squeeze chest at the top'],
    equipment: ['dumbbells', 'incline bench'],
    caloriesPerMinute: 6,
  }),
  ex({
    name: 'Decline Barbell Press',
    muscleGroup: { primary: 'chest', secondary: ['triceps'] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'Emphasizes the lower chest with a decline angle.',
    instructions: [
      'Secure your feet on the decline bench.',
      'Unrack the barbell with a medium grip.',
      'Lower the bar to the lower chest.',
      'Press back up to full extension.',
    ],
    tips: ['Have a spotter for safety', 'Keep core braced'],
    equipment: ['barbell', 'decline bench'],
    caloriesPerMinute: 7,
  }),
  ex({
    name: 'Flat Dumbbell Press',
    muscleGroup: { primary: 'chest', secondary: ['triceps', 'shoulders'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Free-weight horizontal press with greater ROM than a barbell.',
    instructions: [
      'Lie flat with a dumbbell in each hand at shoulder level.',
      'Press the weights up until your arms are extended.',
      'Lower slowly until elbows are at 90°.',
      'Repeat for desired reps.',
    ],
    tips: ['Touch dumbbells lightly at top', 'Stay tight through the bench'],
    equipment: ['dumbbells', 'bench'],
    caloriesPerMinute: 6,
  }),
  ex({
    name: 'Dumbbell Fly',
    muscleGroup: { primary: 'chest', secondary: ['shoulders'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Isolation movement for the pec muscles.',
    instructions: [
      'Lie flat holding dumbbells overhead, palms facing each other.',
      'Lower the weights in a wide arc with a slight elbow bend.',
      'Stop at chest level, feeling the stretch.',
      'Squeeze the chest to return to start.',
    ],
    tips: ['Keep the same elbow angle throughout', 'Use lighter weight than presses'],
    equipment: ['dumbbells', 'bench'],
    caloriesPerMinute: 5,
  }),
  ex({
    name: 'Cable Crossover',
    muscleGroup: { primary: 'chest', secondary: ['shoulders'] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'Constant-tension chest isolation.',
    instructions: [
      'Set cable pulleys to high position.',
      'Step forward holding both handles.',
      'Bring hands together in front of your chest.',
      'Return with control.',
    ],
    tips: ['Slight forward lean targets lower chest', 'Squeeze for a beat at the bottom'],
    equipment: ['cable machine'],
    caloriesPerMinute: 5,
  }),
  ex({
    name: 'Push-Up',
    muscleGroup: { primary: 'chest', secondary: ['triceps', 'core', 'shoulders'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Bodyweight pressing classic.',
    instructions: [
      'Start in a plank, hands shoulder-width apart.',
      'Lower until your chest is just above the floor.',
      'Press back up to start.',
      'Keep your body in a straight line.',
    ],
    tips: ['Elbows ~45° from torso', 'Brace your core'],
    equipment: ['bodyweight'],
    caloriesPerMinute: 7,
  }),
  ex({
    name: 'Diamond Push-Up',
    muscleGroup: { primary: 'triceps', secondary: ['chest'] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'Close-grip push-up emphasising the triceps.',
    instructions: [
      'Place hands together forming a diamond shape.',
      'Lower chest to your hands.',
      'Press back up to start.',
    ],
    tips: ['Keep elbows tucked', 'Drop to knees if needed'],
    equipment: ['bodyweight'],
    caloriesPerMinute: 7,
  }),
  ex({
    name: 'Chest Dip',
    muscleGroup: { primary: 'chest', secondary: ['triceps', 'shoulders'] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'Bodyweight dip with forward lean to bias the chest.',
    instructions: [
      'Grip the parallel bars and support your bodyweight.',
      'Lean your torso forward.',
      'Lower until elbows reach 90°.',
      'Press back up.',
    ],
    tips: ['Forward lean = chest focus', 'Upright torso shifts to triceps'],
    equipment: ['dip bars'],
    caloriesPerMinute: 8,
  }),
  ex({
    name: 'Pec Deck Machine',
    muscleGroup: { primary: 'chest', secondary: [] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Machine fly with a fixed plane of motion.',
    instructions: [
      'Sit with back flat against the pad.',
      'Grip the handles, elbows slightly bent.',
      'Squeeze the pads together in front of your chest.',
      'Return slowly.',
    ],
    tips: ['Match seat height to chest', 'Pause at peak contraction'],
    equipment: ['pec deck'],
    caloriesPerMinute: 5,
  }),

  // ────────── BACK ──────────
  ex({
    name: 'Pull-Up',
    muscleGroup: { primary: 'back', secondary: ['biceps', 'core'] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'Bodyweight king for back width.',
    instructions: [
      'Grip a pull-up bar wider than shoulder width.',
      'Pull yourself up until your chin clears the bar.',
      'Lower with control to a full hang.',
    ],
    tips: ['Drive elbows down, not back', 'Use a band for assistance if needed'],
    equipment: ['pull-up bar'],
    caloriesPerMinute: 9,
  }),
  ex({
    name: 'Chin-Up',
    muscleGroup: { primary: 'back', secondary: ['biceps'] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'Underhand pull-up — biceps get more involvement.',
    instructions: [
      'Grip the bar with palms facing you, shoulder-width.',
      'Pull until your chin clears the bar.',
      'Lower with control.',
    ],
    tips: ['Engage lats first', 'Avoid kipping'],
    equipment: ['pull-up bar'],
    caloriesPerMinute: 9,
  }),
  ex({
    name: 'Lat Pulldown',
    muscleGroup: { primary: 'back', secondary: ['biceps'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Machine pulldown — great for building the pull-up.',
    instructions: [
      'Sit at the machine and grip the bar wider than shoulders.',
      'Pull the bar down to upper chest.',
      'Squeeze lats at the bottom.',
      'Control the bar back up.',
    ],
    tips: ['Lean back slightly, no swinging', 'Initiate with the lats'],
    equipment: ['cable machine'],
    caloriesPerMinute: 6,
  }),
  ex({
    name: 'Bent Over Barbell Row',
    muscleGroup: { primary: 'back', secondary: ['biceps', 'rear delts'] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'Compound mass-builder for the back.',
    instructions: [
      'Hinge at the hips with a slight knee bend, back flat.',
      'Grip the bar overhand at shoulder width.',
      'Row the bar to your lower chest / upper abs.',
      'Lower under control.',
    ],
    tips: ['Keep core braced', 'Pull elbows back, not up'],
    equipment: ['barbell'],
    caloriesPerMinute: 7,
  }),
  ex({
    name: 'T-Bar Row',
    muscleGroup: { primary: 'back', secondary: ['biceps'] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'Heavy supported row variation.',
    instructions: [
      'Straddle the T-Bar handle, knees bent and back flat.',
      'Pull the handle toward your chest.',
      'Squeeze your shoulder blades.',
      'Lower with control.',
    ],
    tips: ['Chest up throughout', 'Use a neutral grip for more lat'],
    equipment: ['t-bar row machine'],
    caloriesPerMinute: 7,
  }),
  ex({
    name: 'Seated Cable Row',
    muscleGroup: { primary: 'back', secondary: ['biceps', 'rear delts'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Constant-tension horizontal pull.',
    instructions: [
      'Sit at the row station, feet on platform, knees slightly bent.',
      'Grab the handle with both hands.',
      'Pull to your abdomen, squeezing the shoulder blades.',
      'Extend arms back without rounding the back.',
    ],
    tips: ['Sit tall', 'Pause briefly at full contraction'],
    equipment: ['cable machine'],
    caloriesPerMinute: 6,
  }),
  ex({
    name: 'Single-Arm Dumbbell Row',
    muscleGroup: { primary: 'back', secondary: ['biceps'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Unilateral back exercise for balanced development.',
    instructions: [
      'Place one knee and hand on a bench.',
      'Hold a dumbbell in your free hand, arm extended.',
      'Row the dumbbell to your hip.',
      'Lower with control.',
    ],
    tips: ['Keep torso parallel to floor', 'Drive elbow back, not up'],
    equipment: ['dumbbell', 'bench'],
    caloriesPerMinute: 6,
  }),
  ex({
    name: 'Conventional Deadlift',
    muscleGroup: { primary: 'back', secondary: ['glutes', 'hamstrings', 'core'] },
    category: 'strength',
    difficulty: 'elite',
    description: 'The full-body strength benchmark.',
    instructions: [
      'Stand with feet hip-width apart, bar over mid-foot.',
      'Hinge to grip the bar just outside knees.',
      'Brace, then drive through the floor to stand up.',
      'Lock out with hips and knees fully extended.',
      'Return the bar to the floor with control.',
    ],
    tips: ['Neutral spine throughout', 'Bar travels in a straight line', 'Reset every rep'],
    equipment: ['barbell'],
    caloriesPerMinute: 10,
  }),
  ex({
    name: 'Romanian Deadlift',
    muscleGroup: { primary: 'hamstrings', secondary: ['glutes', 'back'] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'Hip-hinge focused on the posterior chain.',
    instructions: [
      'Hold a barbell at the hips.',
      'Push hips back, keeping knees slightly bent.',
      'Lower the bar along the legs until you feel a hamstring stretch.',
      'Drive hips forward to return.',
    ],
    tips: ['Bar stays close to legs', 'Stop short of rounding the back'],
    equipment: ['barbell'],
    caloriesPerMinute: 7,
  }),
  ex({
    name: 'Face Pull',
    muscleGroup: { primary: 'rear delts', secondary: ['back', 'rotator cuff'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Shoulder health and rear delt builder.',
    instructions: [
      'Set a cable rope at face height.',
      'Pull the rope to your forehead, splitting the ends apart.',
      'Squeeze the rear delts.',
      'Return with control.',
    ],
    tips: ['Elbows high', 'Light weight, high reps'],
    equipment: ['cable machine'],
    caloriesPerMinute: 5,
  }),
  ex({
    name: 'Barbell Shrug',
    muscleGroup: { primary: 'traps', secondary: ['back'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Direct trapezius builder.',
    instructions: [
      'Hold a barbell with an overhand grip at hip level.',
      'Lift shoulders straight up toward your ears.',
      'Hold and squeeze for a beat.',
      'Lower under control.',
    ],
    tips: ['Avoid rolling shoulders', 'Use a controlled tempo'],
    equipment: ['barbell'],
    caloriesPerMinute: 5,
  }),

  // ────────── SHOULDERS ──────────
  ex({
    name: 'Overhead Barbell Press',
    muscleGroup: { primary: 'shoulders', secondary: ['triceps', 'core'] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'Standing strict press — the gold standard for shoulders.',
    instructions: [
      'Stand with the bar at shoulder level, grip just outside shoulders.',
      'Brace the core and squeeze glutes.',
      'Press the bar overhead until elbows lock.',
      'Lower under control to the shoulders.',
    ],
    tips: ['Tuck chin as the bar passes', 'No leg drive — that becomes a push press'],
    equipment: ['barbell', 'rack'],
    caloriesPerMinute: 7,
  }),
  ex({
    name: 'Seated Dumbbell Shoulder Press',
    muscleGroup: { primary: 'shoulders', secondary: ['triceps'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Supported overhead press.',
    instructions: [
      'Sit on an upright bench with dumbbells at shoulder level.',
      'Press the dumbbells overhead.',
      'Lower with control.',
    ],
    tips: ['Avoid arching your back', 'Press straight up, not forward'],
    equipment: ['dumbbells', 'bench'],
    caloriesPerMinute: 6,
  }),
  ex({
    name: 'Arnold Press',
    muscleGroup: { primary: 'shoulders', secondary: ['triceps'] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'Rotational dumbbell press hitting all three deltoid heads.',
    instructions: [
      'Start with dumbbells in front of shoulders, palms facing you.',
      'Press up while rotating your palms forward.',
      'Lock out overhead.',
      'Reverse the motion to return.',
    ],
    tips: ['Smooth rotation', 'Use moderate weight'],
    equipment: ['dumbbells'],
    caloriesPerMinute: 6,
  }),
  ex({
    name: 'Dumbbell Lateral Raise',
    muscleGroup: { primary: 'shoulders', secondary: [] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Side delt isolation for that capped look.',
    instructions: [
      'Stand with a dumbbell in each hand at your sides.',
      'Raise arms out to shoulder height with a slight elbow bend.',
      'Pause at the top.',
      'Lower slowly.',
    ],
    tips: ['Lead with the elbows', 'No swinging — go light'],
    equipment: ['dumbbells'],
    caloriesPerMinute: 5,
  }),
  ex({
    name: 'Front Raise',
    muscleGroup: { primary: 'shoulders', secondary: [] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Front delt isolation.',
    instructions: [
      'Hold dumbbells in front of your thighs.',
      'Raise one or both arms to shoulder height.',
      'Lower with control.',
    ],
    tips: ['Keep core tight', 'Slight bend in the elbows'],
    equipment: ['dumbbells'],
    caloriesPerMinute: 5,
  }),
  ex({
    name: 'Reverse Pec Deck',
    muscleGroup: { primary: 'rear delts', secondary: ['back'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Rear delt isolation on the machine.',
    instructions: [
      'Sit facing the pec deck, chest against pad.',
      'Grip the handles and pull them out to the sides.',
      'Squeeze rear delts at the back.',
      'Return slowly.',
    ],
    tips: ['Lead with elbows', 'Light weight, high reps'],
    equipment: ['pec deck'],
    caloriesPerMinute: 5,
  }),
  ex({
    name: 'Barbell Upright Row',
    muscleGroup: { primary: 'shoulders', secondary: ['traps'] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'Pulls the bar up the body, hitting delts and traps.',
    instructions: [
      'Hold a barbell with a shoulder-width grip in front of your thighs.',
      'Pull the bar up to chest height, leading with elbows.',
      'Lower under control.',
    ],
    tips: ['Avoid going too narrow on the grip', 'Stop at chest height'],
    equipment: ['barbell'],
    caloriesPerMinute: 6,
  }),
  ex({
    name: 'Push Press',
    muscleGroup: { primary: 'shoulders', secondary: ['triceps', 'legs'] },
    category: 'strength',
    difficulty: 'elite',
    description: 'Overhead press with a leg drive — heavier than strict press.',
    instructions: [
      'Take the bar at shoulder level.',
      'Quarter-squat, then explode up driving the bar overhead.',
      'Lock out arms and reset.',
    ],
    tips: ['Power comes from the hips', 'Catch in a stable lockout'],
    equipment: ['barbell'],
    caloriesPerMinute: 9,
  }),

  // ────────── BICEPS ──────────
  ex({
    name: 'Barbell Curl',
    muscleGroup: { primary: 'biceps', secondary: ['forearms'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Classic biceps builder.',
    instructions: [
      'Hold a barbell with shoulder-width underhand grip.',
      'Curl the bar to your shoulders.',
      'Squeeze and lower slowly.',
    ],
    tips: ['No swinging', 'Keep elbows pinned at your sides'],
    equipment: ['barbell'],
    caloriesPerMinute: 5,
  }),
  ex({
    name: 'Dumbbell Curl',
    muscleGroup: { primary: 'biceps', secondary: ['forearms'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Alternating or simultaneous curls.',
    instructions: [
      'Hold a dumbbell in each hand, palms forward.',
      'Curl the weight to shoulder level.',
      'Lower with control.',
    ],
    tips: ['Supinate fully at the top', 'Slow eccentric'],
    equipment: ['dumbbells'],
    caloriesPerMinute: 5,
  }),
  ex({
    name: 'Hammer Curl',
    muscleGroup: { primary: 'biceps', secondary: ['forearms', 'brachialis'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Neutral-grip curl targeting the brachialis.',
    instructions: [
      'Hold dumbbells with palms facing your body.',
      'Curl upward, keeping palms facing in.',
      'Lower under control.',
    ],
    tips: ['Great for arm thickness', 'Don\'t rotate the wrist'],
    equipment: ['dumbbells'],
    caloriesPerMinute: 5,
  }),
  ex({
    name: 'Preacher Curl',
    muscleGroup: { primary: 'biceps', secondary: ['forearms'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Strict curl that eliminates body english.',
    instructions: [
      'Rest your upper arms on a preacher bench.',
      'Curl an EZ-bar or dumbbells up.',
      'Lower until elbows are nearly extended.',
    ],
    tips: ['Stop short of locking out at the bottom', 'Squeeze hard at the top'],
    equipment: ['preacher bench', 'ez-bar'],
    caloriesPerMinute: 5,
  }),
  ex({
    name: 'Cable Curl',
    muscleGroup: { primary: 'biceps', secondary: ['forearms'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Constant-tension cable curl.',
    instructions: [
      'Attach a straight bar to a low pulley.',
      'Curl the bar to your shoulders.',
      'Lower slowly.',
    ],
    tips: ['Step back so the cable angles up', 'Keep elbows fixed'],
    equipment: ['cable machine'],
    caloriesPerMinute: 5,
  }),
  ex({
    name: 'Concentration Curl',
    muscleGroup: { primary: 'biceps', secondary: [] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Seated single-arm peak biceps curl.',
    instructions: [
      'Sit on a bench, elbow braced against inner thigh.',
      'Curl the dumbbell up.',
      'Lower slowly.',
    ],
    tips: ['Lock the elbow in place', 'Visualise the squeeze'],
    equipment: ['dumbbell', 'bench'],
    caloriesPerMinute: 4,
  }),
  ex({
    name: 'Incline Dumbbell Curl',
    muscleGroup: { primary: 'biceps', secondary: [] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'Increased stretch on the long head of the biceps.',
    instructions: [
      'Lie back on a 45° incline bench with dumbbells at your sides.',
      'Curl the dumbbells up, supinating as you go.',
      'Lower slowly under control.',
    ],
    tips: ['Let the arms hang fully at the bottom', 'No swinging'],
    equipment: ['dumbbells', 'incline bench'],
    caloriesPerMinute: 5,
  }),

  // ────────── TRICEPS ──────────
  ex({
    name: 'Tricep Pushdown',
    muscleGroup: { primary: 'triceps', secondary: [] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Cable pushdown for triceps isolation.',
    instructions: [
      'Stand at a high cable with a bar attachment.',
      'Push the bar down until arms are fully extended.',
      'Slowly return to start.',
    ],
    tips: ['Keep elbows pinned to your ribs', 'Squeeze at full extension'],
    equipment: ['cable machine'],
    caloriesPerMinute: 5,
  }),
  ex({
    name: 'Skull Crusher',
    muscleGroup: { primary: 'triceps', secondary: [] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'Lying tricep extension.',
    instructions: [
      'Lie flat with an EZ-bar or dumbbells held overhead.',
      'Bend the elbows to lower the weight to your forehead.',
      'Extend back to start.',
    ],
    tips: ['Keep upper arms vertical', 'Use moderate weight to protect elbows'],
    equipment: ['ez-bar', 'bench'],
    caloriesPerMinute: 5,
  }),
  ex({
    name: 'Overhead Tricep Extension',
    muscleGroup: { primary: 'triceps', secondary: [] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Overhead extension that stretches the long head.',
    instructions: [
      'Hold a dumbbell with both hands overhead.',
      'Bend the elbows to lower the weight behind your head.',
      'Extend back to start.',
    ],
    tips: ['Keep elbows pointed forward', 'Avoid flaring'],
    equipment: ['dumbbell'],
    caloriesPerMinute: 5,
  }),
  ex({
    name: 'Close-Grip Bench Press',
    muscleGroup: { primary: 'triceps', secondary: ['chest', 'shoulders'] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'Tricep-biased pressing variant.',
    instructions: [
      'Set up like a bench press but grip shoulder-width.',
      'Lower the bar to the lower chest, elbows tucked.',
      'Press back up.',
    ],
    tips: ['Don\'t go narrower than shoulder width — bad for wrists', 'Tuck the elbows'],
    equipment: ['barbell', 'bench'],
    caloriesPerMinute: 7,
  }),
  ex({
    name: 'Tricep Dip',
    muscleGroup: { primary: 'triceps', secondary: ['chest', 'shoulders'] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'Bodyweight dip with upright torso for tricep focus.',
    instructions: [
      'Support yourself on parallel bars.',
      'Keep torso upright.',
      'Lower until elbows hit 90°.',
      'Press back up.',
    ],
    tips: ['Lock out fully', 'Add weight when bodyweight is easy'],
    equipment: ['dip bars'],
    caloriesPerMinute: 8,
  }),
  ex({
    name: 'Rope Tricep Pushdown',
    muscleGroup: { primary: 'triceps', secondary: [] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Rope variation allows more spread at the bottom.',
    instructions: [
      'Attach a rope to a high cable.',
      'Push down and spread the rope ends out at the bottom.',
      'Return to start.',
    ],
    tips: ['Pull the rope apart at lockout', 'Keep elbows fixed'],
    equipment: ['cable machine'],
    caloriesPerMinute: 5,
  }),

  // ────────── LEGS ──────────
  ex({
    name: 'Barbell Back Squat',
    muscleGroup: { primary: 'quads', secondary: ['glutes', 'hamstrings', 'core'] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'The king of leg exercises.',
    instructions: [
      'Place the bar across your upper back.',
      'Stand with feet shoulder-width, toes slightly out.',
      'Squat down by pushing hips back and bending knees.',
      'Descend until thighs are parallel or below.',
      'Drive back up through midfoot.',
    ],
    tips: ['Brace your core hard', 'Knees track over toes', 'Chest up'],
    equipment: ['barbell', 'rack'],
    caloriesPerMinute: 9,
  }),
  ex({
    name: 'Front Squat',
    muscleGroup: { primary: 'quads', secondary: ['core', 'upper back'] },
    category: 'strength',
    difficulty: 'elite',
    description: 'Front-rack squat that emphasises the quads and trunk.',
    instructions: [
      'Rack the bar on your front delts, elbows high.',
      'Squat down keeping torso upright.',
      'Drive back up.',
    ],
    tips: ['Keep elbows up', 'Mobile wrists/shoulders required'],
    equipment: ['barbell', 'rack'],
    caloriesPerMinute: 9,
  }),
  ex({
    name: 'Goblet Squat',
    muscleGroup: { primary: 'quads', secondary: ['glutes', 'core'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Dumbbell squat — a great teaching tool.',
    instructions: [
      'Hold a dumbbell at chest height.',
      'Squat down keeping chest up and elbows inside knees.',
      'Stand back up.',
    ],
    tips: ['Use for warm-up sets', 'Pause briefly at the bottom'],
    equipment: ['dumbbell'],
    caloriesPerMinute: 7,
  }),
  ex({
    name: 'Walking Lunge',
    muscleGroup: { primary: 'quads', secondary: ['glutes', 'hamstrings'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Dynamic lower-body builder.',
    instructions: [
      'Hold dumbbells at your sides.',
      'Step forward and lower the back knee toward the floor.',
      'Drive up and step forward with the other leg.',
    ],
    tips: ['Long stride', 'Stay tall through the torso'],
    equipment: ['dumbbells'],
    caloriesPerMinute: 8,
  }),
  ex({
    name: 'Bulgarian Split Squat',
    muscleGroup: { primary: 'quads', secondary: ['glutes'] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'Rear-foot-elevated split squat for single-leg strength.',
    instructions: [
      'Place one foot behind you on a bench.',
      'Lunge down with the front leg.',
      'Drive up to standing.',
    ],
    tips: ['Front knee tracks over toes', 'Goblet-hold or DBs by sides'],
    equipment: ['dumbbells', 'bench'],
    caloriesPerMinute: 8,
  }),
  ex({
    name: 'Leg Press',
    muscleGroup: { primary: 'quads', secondary: ['glutes', 'hamstrings'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Machine compound for the lower body.',
    instructions: [
      'Sit on the leg press machine.',
      'Place feet shoulder-width on the platform.',
      'Lower the platform until knees are at 90°.',
      'Press back up without locking knees.',
    ],
    tips: ['Don\'t lift hips off the seat', 'Feet higher = more glutes/hams'],
    equipment: ['leg press machine'],
    caloriesPerMinute: 8,
  }),
  ex({
    name: 'Leg Curl',
    muscleGroup: { primary: 'hamstrings', secondary: [] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Hamstring isolation on a machine.',
    instructions: [
      'Lie on the leg curl machine, pads on lower legs.',
      'Curl the heels toward your glutes.',
      'Lower with control.',
    ],
    tips: ['Squeeze at the top', 'Don\'t rush the eccentric'],
    equipment: ['leg curl machine'],
    caloriesPerMinute: 5,
  }),
  ex({
    name: 'Leg Extension',
    muscleGroup: { primary: 'quads', secondary: [] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Quad isolation on a machine.',
    instructions: [
      'Sit at the leg extension machine.',
      'Extend legs fully until knees are straight.',
      'Lower under control.',
    ],
    tips: ['Pause at the top', 'Lighter weights for more reps'],
    equipment: ['leg extension machine'],
    caloriesPerMinute: 5,
  }),
  ex({
    name: 'Standing Calf Raise',
    muscleGroup: { primary: 'calves', secondary: [] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Vertical calf raise for the gastrocnemius.',
    instructions: [
      'Stand on a calf-raise machine or step.',
      'Rise up onto the balls of your feet.',
      'Lower below the platform for a stretch.',
    ],
    tips: ['Pause at the top', 'Slow eccentrics'],
    equipment: ['calf raise machine'],
    caloriesPerMinute: 5,
  }),
  ex({
    name: 'Hip Thrust',
    muscleGroup: { primary: 'glutes', secondary: ['hamstrings'] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'Glute-dominant hip extension.',
    instructions: [
      'Sit with upper back on a bench, barbell across hips.',
      'Drive hips up until torso is parallel with the floor.',
      'Squeeze glutes hard at the top.',
      'Lower with control.',
    ],
    tips: ['Tuck chin', 'Use a pad on the bar'],
    equipment: ['barbell', 'bench'],
    caloriesPerMinute: 7,
  }),
  ex({
    name: 'Sumo Deadlift',
    muscleGroup: { primary: 'glutes', secondary: ['quads', 'back'] },
    category: 'strength',
    difficulty: 'elite',
    description: 'Wide-stance deadlift, more leg drive than conventional.',
    instructions: [
      'Stand with feet very wide, toes pointed out.',
      'Grip the bar with hands inside knees.',
      'Drive through the floor to stand up.',
    ],
    tips: ['Push knees out throughout', 'Stay vertical'],
    equipment: ['barbell'],
    caloriesPerMinute: 10,
  }),
  ex({
    name: 'Hack Squat',
    muscleGroup: { primary: 'quads', secondary: ['glutes'] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'Sled squat machine with a fixed plane.',
    instructions: [
      'Position yourself on the hack squat machine.',
      'Lower until thighs are parallel.',
      'Press back up.',
    ],
    tips: ['Foot placement changes muscle bias', 'Don\'t lock out hard at the top'],
    equipment: ['hack squat machine'],
    caloriesPerMinute: 8,
  }),
  ex({
    name: 'Step-Up',
    muscleGroup: { primary: 'quads', secondary: ['glutes', 'hamstrings'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Single-leg step-up onto a box or bench.',
    instructions: [
      'Place one foot on a sturdy box at knee height.',
      'Drive through the heel to stand up.',
      'Lower with control.',
    ],
    tips: ['Don\'t push off the bottom leg', 'Keep chest up'],
    equipment: ['box', 'dumbbells'],
    caloriesPerMinute: 7,
  }),

  // ────────── CORE ──────────
  ex({
    name: 'Plank',
    muscleGroup: { primary: 'core', secondary: ['shoulders', 'glutes'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Isometric anti-extension core hold.',
    instructions: [
      'Get into a forearm plank position.',
      'Brace abs and glutes.',
      'Hold a straight line from heels to head.',
    ],
    tips: ['Don\'t let hips sag', 'Breathe shallow and steady'],
    equipment: ['bodyweight'],
    caloriesPerMinute: 5,
  }),
  ex({
    name: 'Side Plank',
    muscleGroup: { primary: 'core', secondary: ['shoulders'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Lateral hold for the obliques.',
    instructions: [
      'Lie on your side with elbow under shoulder.',
      'Lift hips so body forms a straight line.',
      'Hold.',
    ],
    tips: ['Stack your feet or stagger them', 'Lift hips high'],
    equipment: ['bodyweight'],
    caloriesPerMinute: 5,
  }),
  ex({
    name: 'Crunch',
    muscleGroup: { primary: 'core', secondary: [] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Basic ab crunch.',
    instructions: [
      'Lie on your back, knees bent.',
      'Curl shoulders off the floor toward your knees.',
      'Lower under control.',
    ],
    tips: ['Don\'t pull on your neck', 'Exhale on the way up'],
    equipment: ['bodyweight'],
    caloriesPerMinute: 5,
  }),
  ex({
    name: 'Russian Twist',
    muscleGroup: { primary: 'core', secondary: [] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Rotational core exercise.',
    instructions: [
      'Sit with knees bent, leaned back slightly.',
      'Rotate the torso to touch the floor on each side.',
    ],
    tips: ['Hold a weight for resistance', 'Move the torso, not just the arms'],
    equipment: ['bodyweight', 'medicine ball'],
    caloriesPerMinute: 6,
  }),
  ex({
    name: 'Hanging Leg Raise',
    muscleGroup: { primary: 'core', secondary: ['hip flexors'] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'Lower-ab focused hanging exercise.',
    instructions: [
      'Hang from a pull-up bar.',
      'Raise straight legs to horizontal (or higher).',
      'Lower with control — no swinging.',
    ],
    tips: ['Posterior tilt at the top', 'Knee tucks if too hard'],
    equipment: ['pull-up bar'],
    caloriesPerMinute: 6,
  }),
  ex({
    name: 'Bicycle Crunch',
    muscleGroup: { primary: 'core', secondary: ['obliques'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Alternating crunch with a leg cycle.',
    instructions: [
      'Lie on your back, hands behind ears.',
      'Bring opposite elbow to opposite knee.',
      'Alternate sides in a cycling motion.',
    ],
    tips: ['Slow and controlled beats speed', 'Don\'t pull on the neck'],
    equipment: ['bodyweight'],
    caloriesPerMinute: 6,
  }),
  ex({
    name: 'Cable Crunch',
    muscleGroup: { primary: 'core', secondary: [] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'Weighted ab crunch using a cable.',
    instructions: [
      'Kneel facing a high cable, rope behind your head.',
      'Crunch down, contracting the abs.',
      'Return slowly.',
    ],
    tips: ['Use the abs, not the hips', 'Round the spine slightly'],
    equipment: ['cable machine'],
    caloriesPerMinute: 5,
  }),
  ex({
    name: 'Dead Bug',
    muscleGroup: { primary: 'core', secondary: [] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Anti-extension exercise for spinal stability.',
    instructions: [
      'Lie on your back, arms up, knees over hips.',
      'Lower opposite arm and leg slowly.',
      'Return and repeat the other side.',
    ],
    tips: ['Keep lower back pinned to floor', 'Slow tempo'],
    equipment: ['bodyweight'],
    caloriesPerMinute: 4,
  }),
  ex({
    name: 'Ab Wheel Rollout',
    muscleGroup: { primary: 'core', secondary: ['shoulders'] },
    category: 'strength',
    difficulty: 'elite',
    description: 'Advanced anti-extension exercise.',
    instructions: [
      'Kneel holding an ab wheel.',
      'Roll out as far as you can control.',
      'Roll back to start.',
    ],
    tips: ['Don\'t let the hips drop', 'Build up from knees'],
    equipment: ['ab wheel'],
    caloriesPerMinute: 6,
  }),

  // ────────── CARDIO ──────────
  ex({
    name: 'Treadmill Run',
    muscleGroup: { primary: 'cardio', secondary: ['legs'] },
    category: 'cardio',
    difficulty: 'beginner',
    description: 'Steady-state or interval running.',
    instructions: [
      'Set the treadmill to a comfortable pace.',
      'Maintain good posture and steady breathing.',
    ],
    tips: ['Vary incline for harder workouts', 'Warm up for 5 minutes'],
    equipment: ['treadmill'],
    caloriesPerMinute: 11,
  }),
  ex({
    name: 'Stationary Bike',
    muscleGroup: { primary: 'cardio', secondary: ['legs'] },
    category: 'cardio',
    difficulty: 'beginner',
    description: 'Low-impact cardio session.',
    instructions: [
      'Adjust seat height so knees are slightly bent at full extension.',
      'Ride at steady tempo or alternate intensities.',
    ],
    tips: ['Maintain cadence ~80-100 rpm', 'Push and pull through the pedals'],
    equipment: ['bike'],
    caloriesPerMinute: 8,
  }),
  ex({
    name: 'Rowing Machine',
    muscleGroup: { primary: 'cardio', secondary: ['back', 'legs', 'core'] },
    category: 'cardio',
    difficulty: 'intermediate',
    description: 'Full-body cardio with a strong pulling component.',
    instructions: [
      'Sit with shins vertical, arms forward.',
      'Drive with the legs first, then lean back, then pull the handle.',
      'Reverse the motion to return.',
    ],
    tips: ['Legs, body, arms — in that order', 'Don\'t round the back'],
    equipment: ['rower'],
    caloriesPerMinute: 12,
  }),
  ex({
    name: 'Jump Rope',
    muscleGroup: { primary: 'cardio', secondary: ['calves', 'shoulders'] },
    category: 'cardio',
    difficulty: 'beginner',
    description: 'High-intensity coordination cardio.',
    instructions: [
      'Hold rope handles with arms relaxed.',
      'Use wrists to spin the rope.',
      'Hop just enough to clear it.',
    ],
    tips: ['Land softly on the balls of your feet', 'Stay relaxed'],
    equipment: ['jump rope'],
    caloriesPerMinute: 13,
  }),
  ex({
    name: 'Stair Climber',
    muscleGroup: { primary: 'cardio', secondary: ['glutes', 'legs'] },
    category: 'cardio',
    difficulty: 'intermediate',
    description: 'Stepping cardio with strong glute involvement.',
    instructions: [
      'Step onto the climber and start moving.',
      'Stand tall — don\'t hunch over the rails.',
    ],
    tips: ['Lean slightly forward at hips', 'Don\'t lean on the rails'],
    equipment: ['stair climber'],
    caloriesPerMinute: 10,
  }),
  ex({
    name: 'Elliptical',
    muscleGroup: { primary: 'cardio', secondary: ['legs', 'glutes'] },
    category: 'cardio',
    difficulty: 'beginner',
    description: 'Joint-friendly low-impact cardio.',
    instructions: [
      'Step onto the elliptical, grip the moving handles.',
      'Move in a smooth striding motion.',
    ],
    tips: ['Push and pull', 'Adjust resistance for harder work'],
    equipment: ['elliptical'],
    caloriesPerMinute: 9,
  }),
  ex({
    name: 'Burpees',
    muscleGroup: { primary: 'cardio', secondary: ['full body'] },
    category: 'cardio',
    difficulty: 'intermediate',
    description: 'Full-body conditioner.',
    instructions: [
      'From standing, drop into a squat, hands down.',
      'Kick legs back to a plank.',
      'Do a push-up.',
      'Jump feet back, then explode upward.',
    ],
    tips: ['Pace yourself — they burn fast', 'Skip the push-up for an easier version'],
    equipment: ['bodyweight'],
    caloriesPerMinute: 13,
  }),
  ex({
    name: 'Mountain Climbers',
    muscleGroup: { primary: 'cardio', secondary: ['core', 'shoulders'] },
    category: 'cardio',
    difficulty: 'beginner',
    description: 'Plank with alternating knee drives.',
    instructions: [
      'Start in a high plank.',
      'Drive one knee to your chest, then alternate quickly.',
    ],
    tips: ['Keep hips low', 'Don\'t bounce'],
    equipment: ['bodyweight'],
    caloriesPerMinute: 11,
  }),

  // ────────── HIIT ──────────
  ex({
    name: 'Box Jump',
    muscleGroup: { primary: 'legs', secondary: ['cardio'] },
    category: 'HIIT',
    difficulty: 'intermediate',
    description: 'Explosive plyometric jump onto a box.',
    instructions: [
      'Stand facing a sturdy box.',
      'Drop into a quarter-squat and swing arms back.',
      'Explode up and land softly on the box.',
      'Step (don\'t jump) down.',
    ],
    tips: ['Land softly with bent knees', 'Step down to save your knees'],
    equipment: ['plyo box'],
    caloriesPerMinute: 11,
  }),
  ex({
    name: 'Kettlebell Swing',
    muscleGroup: { primary: 'glutes', secondary: ['hamstrings', 'core', 'cardio'] },
    category: 'HIIT',
    difficulty: 'intermediate',
    description: 'Explosive hip hinge with a kettlebell.',
    instructions: [
      'Stand over a kettlebell with feet hip-width.',
      'Hinge to grip the bell.',
      'Hike it between your legs, then snap hips forward to swing it to chest height.',
      'Reverse the motion.',
    ],
    tips: ['Power from the hips — not the arms', 'Glute squeeze at the top'],
    equipment: ['kettlebell'],
    caloriesPerMinute: 12,
  }),
  ex({
    name: 'Battle Ropes',
    muscleGroup: { primary: 'shoulders', secondary: ['core', 'cardio'] },
    category: 'HIIT',
    difficulty: 'intermediate',
    description: 'Conditioning with heavy ropes.',
    instructions: [
      'Stand in a quarter-squat holding the rope ends.',
      'Slam, wave, or alternate-wave the ropes for time.',
    ],
    tips: ['Brace the core', 'Short, intense intervals'],
    equipment: ['battle ropes'],
    caloriesPerMinute: 11,
  }),
  ex({
    name: 'Sled Push',
    muscleGroup: { primary: 'legs', secondary: ['cardio', 'core'] },
    category: 'HIIT',
    difficulty: 'intermediate',
    description: 'Push a weighted sled across the floor.',
    instructions: [
      'Grip the sled handles, body angled forward.',
      'Drive through the legs to push the sled.',
    ],
    tips: ['Stay low for max drive', 'Push for short, hard intervals'],
    equipment: ['sled'],
    caloriesPerMinute: 14,
  }),
  ex({
    name: 'Sprint Intervals',
    muscleGroup: { primary: 'cardio', secondary: ['legs'] },
    category: 'HIIT',
    difficulty: 'intermediate',
    description: 'Short max-effort runs with rest.',
    instructions: [
      'Sprint at max effort for 20-30 seconds.',
      'Rest or walk for 60-90 seconds.',
      'Repeat for 6-10 rounds.',
    ],
    tips: ['Warm up thoroughly', 'Full recovery between sprints'],
    equipment: ['track or treadmill'],
    caloriesPerMinute: 15,
  }),
  ex({
    name: 'Wall Ball',
    muscleGroup: { primary: 'legs', secondary: ['shoulders', 'cardio'] },
    category: 'HIIT',
    difficulty: 'intermediate',
    description: 'Squat-and-throw with a medicine ball.',
    instructions: [
      'Hold a medicine ball at your chest.',
      'Squat down.',
      'Drive up and throw the ball at a target on the wall.',
      'Catch and repeat.',
    ],
    tips: ['Use legs to power the throw', 'Pick a target height ~10ft'],
    equipment: ['medicine ball'],
    caloriesPerMinute: 11,
  }),
  ex({
    name: 'Barbell Thruster',
    muscleGroup: { primary: 'legs', secondary: ['shoulders', 'cardio'] },
    category: 'HIIT',
    difficulty: 'elite',
    description: 'Front squat into overhead press.',
    instructions: [
      'Front rack the bar at shoulders.',
      'Squat down.',
      'Drive up and continue the momentum into an overhead press.',
      'Return the bar to shoulders.',
    ],
    tips: ['One smooth motion', 'Use moderate weight'],
    equipment: ['barbell'],
    caloriesPerMinute: 13,
  }),

  // ────────── FLEXIBILITY ──────────
  ex({
    name: 'Downward Dog',
    muscleGroup: { primary: 'flexibility', secondary: ['hamstrings', 'shoulders'] },
    category: 'flexibility',
    difficulty: 'beginner',
    description: 'Yoga inversion that stretches the posterior chain.',
    instructions: [
      'From a plank, push hips up and back.',
      'Form an inverted V with your body.',
      'Hold and breathe deeply.',
    ],
    tips: ['Pedal the heels to deepen the stretch', 'Open through the chest'],
    equipment: ['mat'],
    caloriesPerMinute: 3,
  }),
  ex({
    name: 'Pigeon Stretch',
    muscleGroup: { primary: 'flexibility', secondary: ['glutes', 'hips'] },
    category: 'flexibility',
    difficulty: 'beginner',
    description: 'Deep hip and glute stretch.',
    instructions: [
      'From a plank, bring one knee under your chest, shin angled.',
      'Lower your back leg to the floor.',
      'Sink your hips and hold.',
    ],
    tips: ['Use a block under the hip if needed', 'Don\'t force depth'],
    equipment: ['mat'],
    caloriesPerMinute: 3,
  }),
  ex({
    name: 'Standing Hamstring Stretch',
    muscleGroup: { primary: 'flexibility', secondary: ['hamstrings'] },
    category: 'flexibility',
    difficulty: 'beginner',
    description: 'Static hamstring stretch.',
    instructions: [
      'Stand with one heel on a low step or box.',
      'Hinge at the hips and reach for your toes.',
      'Hold the stretch.',
    ],
    tips: ['Keep the knee straight but not locked', 'Hinge from hips, not waist'],
    equipment: ['bodyweight'],
    caloriesPerMinute: 2,
  }),
  ex({
    name: 'Cat-Cow Stretch',
    muscleGroup: { primary: 'flexibility', secondary: ['back', 'core'] },
    category: 'flexibility',
    difficulty: 'beginner',
    description: 'Spinal mobility flow.',
    instructions: [
      'Start on hands and knees.',
      'Inhale: drop belly, lift head and tailbone (cow).',
      'Exhale: round spine, tuck chin (cat).',
      'Repeat smoothly.',
    ],
    tips: ['Move with breath', 'Great warm-up'],
    equipment: ['mat'],
    caloriesPerMinute: 3,
  }),
  ex({
    name: 'Hip Flexor Stretch',
    muscleGroup: { primary: 'flexibility', secondary: ['hips'] },
    category: 'flexibility',
    difficulty: 'beginner',
    description: 'Kneeling lunge stretch for the hip flexors.',
    instructions: [
      'Kneel on one knee with the other foot forward.',
      'Tuck your pelvis and gently push hips forward.',
      'Hold the stretch.',
    ],
    tips: ['Squeeze the back-leg glute', 'Stay tall'],
    equipment: ['mat'],
    caloriesPerMinute: 2,
  }),
  ex({
    name: 'Cobra Stretch',
    muscleGroup: { primary: 'flexibility', secondary: ['back', 'core'] },
    category: 'flexibility',
    difficulty: 'beginner',
    description: 'Back-extension stretch for the spine.',
    instructions: [
      'Lie face down with hands under shoulders.',
      'Press the chest off the floor while keeping hips down.',
      'Hold and breathe.',
    ],
    tips: ['Keep elbows soft', 'Don\'t crunch the lower back'],
    equipment: ['mat'],
    caloriesPerMinute: 2,
  }),

  // ────────── HOME / NO-GYM ──────────
  // Bodyweight and household-item moves for anyone training without a gym.
  ex({
    name: 'Glute Bridge',
    muscleGroup: { primary: 'glutes', secondary: ['hamstrings', 'core'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Floor hip extension that fires up the glutes — no equipment needed.',
    instructions: [
      'Lie on your back, knees bent, feet flat and hip-width apart.',
      'Drive through your heels to lift your hips toward the ceiling.',
      'Squeeze your glutes hard at the top.',
      'Lower with control without resting on the floor.',
    ],
    tips: ['Keep ribs down — don\'t arch the lower back', 'Pause for a beat at the top'],
    equipment: ['bodyweight'],
    caloriesPerMinute: 5,
  }),
  ex({
    name: 'Wall Sit',
    muscleGroup: { primary: 'quads', secondary: ['glutes', 'core'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Isometric quad burner you can do against any wall.',
    instructions: [
      'Stand with your back flat against a wall.',
      'Slide down until your thighs are parallel to the floor.',
      'Keep knees over ankles, shins vertical.',
      'Hold for time.',
    ],
    tips: ['Keep your whole back on the wall', 'Hold a backpack on your lap to add load'],
    equipment: ['bodyweight', 'wall'],
    caloriesPerMinute: 5,
  }),
  ex({
    name: 'Reverse Lunge',
    muscleGroup: { primary: 'quads', secondary: ['glutes', 'hamstrings'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Knee-friendly bodyweight lunge — great for small spaces.',
    instructions: [
      'Stand tall, hands on hips or holding water bottles.',
      'Step one foot straight back and lower the back knee toward the floor.',
      'Drive through the front heel to return to standing.',
      'Alternate legs.',
    ],
    tips: ['Keep the front shin vertical', 'Stay tall through the torso'],
    equipment: ['bodyweight'],
    caloriesPerMinute: 7,
  }),
  ex({
    name: 'Pike Push-Up',
    muscleGroup: { primary: 'shoulders', secondary: ['triceps', 'core'] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'Bodyweight shoulder press — the home alternative to overhead pressing.',
    instructions: [
      'Start in a downward-dog / pike position, hips high.',
      'Bend your elbows to lower the crown of your head toward the floor.',
      'Press back up to full extension.',
    ],
    tips: ['The higher your hips, the more shoulder focus', 'Elevate feet on a chair to make it harder'],
    equipment: ['bodyweight'],
    caloriesPerMinute: 7,
  }),
  ex({
    name: 'Chair Dip',
    muscleGroup: { primary: 'triceps', secondary: ['chest', 'shoulders'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Tricep dip off a sturdy chair, couch, or step.',
    instructions: [
      'Sit on the edge of a chair, hands gripping the edge beside your hips.',
      'Slide your hips off the seat.',
      'Bend your elbows to lower until they reach about 90°.',
      'Press back up.',
    ],
    tips: ['Keep elbows pointing back, not flaring out', 'Straighten your legs to make it harder'],
    equipment: ['chair'],
    caloriesPerMinute: 6,
  }),
  ex({
    name: 'Backpack Goblet Squat',
    muscleGroup: { primary: 'quads', secondary: ['glutes', 'core'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Loaded squat using a weighted backpack — no dumbbell required.',
    instructions: [
      'Load a backpack with books or bottles and hug it to your chest.',
      'Stand with feet shoulder-width, toes slightly out.',
      'Squat down, keeping chest up and elbows inside the knees.',
      'Drive back up to standing.',
    ],
    tips: ['Pack the weight tight so it doesn\'t shift', 'Pause briefly at the bottom'],
    equipment: ['backpack'],
    caloriesPerMinute: 7,
  }),
  ex({
    name: 'Superman',
    muscleGroup: { primary: 'back', secondary: ['glutes', 'shoulders'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Floor back extension for the spinal erectors — no gear needed.',
    instructions: [
      'Lie face down, arms extended overhead.',
      'Lift your arms, chest, and legs off the floor at the same time.',
      'Squeeze your glutes and lower back.',
      'Lower with control.',
    ],
    tips: ['Keep your neck neutral — look at the floor', 'Hold for a beat at the top'],
    equipment: ['bodyweight', 'mat'],
    caloriesPerMinute: 4,
  }),
  ex({
    name: 'Bird Dog',
    muscleGroup: { primary: 'core', secondary: ['back', 'glutes'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Anti-rotation core exercise for stability and balance.',
    instructions: [
      'Start on hands and knees, spine neutral.',
      'Extend your opposite arm and leg until they are in line with your torso.',
      'Pause, then return under control.',
      'Alternate sides.',
    ],
    tips: ['Keep hips level — don\'t rotate', 'Move slowly and stay balanced'],
    equipment: ['bodyweight', 'mat'],
    caloriesPerMinute: 4,
  }),
  ex({
    name: 'Flutter Kicks',
    muscleGroup: { primary: 'core', secondary: ['hip flexors'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Lower-ab focused kicks done flat on the floor.',
    instructions: [
      'Lie on your back, hands tucked under your glutes.',
      'Lift both legs a few inches off the floor.',
      'Alternate kicking your legs up and down in small, quick motions.',
    ],
    tips: ['Keep your lower back pinned to the floor', 'Brace your abs throughout'],
    equipment: ['bodyweight', 'mat'],
    caloriesPerMinute: 6,
  }),
  ex({
    name: 'Jumping Jacks',
    muscleGroup: { primary: 'cardio', secondary: ['shoulders', 'calves'] },
    category: 'cardio',
    difficulty: 'beginner',
    description: 'Classic full-body cardio warm-up — needs zero equipment.',
    instructions: [
      'Stand with feet together, arms at your sides.',
      'Jump your feet out wide while raising your arms overhead.',
      'Jump back to the start.',
      'Keep a steady rhythm.',
    ],
    tips: ['Land softly on the balls of your feet', 'Great as a warm-up or finisher'],
    equipment: ['bodyweight'],
    caloriesPerMinute: 9,
  }),
  ex({
    name: 'High Knees',
    muscleGroup: { primary: 'cardio', secondary: ['core', 'legs'] },
    category: 'cardio',
    difficulty: 'beginner',
    description: 'In-place running drive that spikes the heart rate.',
    instructions: [
      'Stand tall and run in place.',
      'Drive each knee up to hip height.',
      'Pump your arms in time with your legs.',
    ],
    tips: ['Stay on the balls of your feet', 'Keep your core tight and tall'],
    equipment: ['bodyweight'],
    caloriesPerMinute: 11,
  }),
  ex({
    name: 'Inchworm',
    muscleGroup: { primary: 'flexibility', secondary: ['core', 'shoulders'] },
    category: 'flexibility',
    difficulty: 'beginner',
    description: 'Dynamic full-body stretch and warm-up.',
    instructions: [
      'Stand tall, then hinge and place your hands on the floor.',
      'Walk your hands out to a plank.',
      'Walk your feet up toward your hands.',
      'Stand and repeat.',
    ],
    tips: ['Keep your legs as straight as comfortable', 'Move slowly and breathe'],
    equipment: ['bodyweight', 'mat'],
    caloriesPerMinute: 5,
  }),
  // Additional exercises: forearm, adductor, abductor, pullover
  ex({
    name: 'Reverse Wrist Curl',
    muscleGroup: { primary: 'forearms', secondary: ['wrist extensors'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Forearm isolation focusing on the wrist extensors.',
    instructions: [
      'Sit with forearms resting on your thighs and wrists hanging over the knees, holding a barbell with an overhand grip.',
      'Curl the bar upward by extending at the wrists while keeping the forearms stationary.',
      'Pause briefly at the top, then lower under control.',
      'Perform controlled reps without using momentum.'
    ],
    tips: ['Use a light-moderate load', 'Control the eccentric for best results'],
    equipment: ['barbell', 'bench'],
    caloriesPerMinute: 4,
  }),
  ex({
    name: 'Standing Cable Hip Adduction',
    muscleGroup: { primary: 'adductors', secondary: ['hip flexors'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Cable-based isolation to strengthen the inner thigh (adductors).',
    instructions: [
      'Attach an ankle cuff to a low cable and secure it to the outside ankle, standing perpendicular to the machine.',
      'Keep the support leg slightly bent and the working leg straight, then pull the cable across the body toward the midline by squeezing the inner thigh.',
      'Control the return to the start position.',
      'Repeat for desired reps and switch sides.'
    ],
    tips: ['Start light to learn the movement', 'Pause briefly at peak contraction'],
    equipment: ['cable machine', 'ankle cuff'],
    caloriesPerMinute: 4,
  }),
  ex({
    name: 'Standing Cable Hip Abduction',
    muscleGroup: { primary: 'abductors', secondary: ['glutes'] },
    category: 'strength',
    difficulty: 'beginner',
    description: 'Cable-based isolation to strengthen the outer hip (abductors).',
    instructions: [
      'Attach an ankle cuff to a low cable and secure it to the inside ankle, standing next to the machine.',
      'Keep the support leg slightly bent and the working leg straight, then move the working leg away from the midline by contracting the outer hip.',
      'Hold briefly at the top, then return under control.',
      'Repeat for reps and switch sides.'
    ],
    tips: ['Control the descent', 'Perform higher reps for endurance'],
    equipment: ['cable machine', 'ankle cuff'],
    caloriesPerMinute: 4,
  }),
  ex({
    name: 'Straight-Arm Dumbbell Pullover',
    muscleGroup: { primary: 'back', secondary: ['chest', 'triceps'] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'Pullover variant that emphasizes the lats while also stretching the chest.',
    instructions: [
      'Lie perpendicular on a bench so only your upper back and shoulders contact the bench, feet flat on the floor.',
      'Hold a dumbbell with both hands over your chest, arms nearly straight with a slight bend in the elbows.',
      'Keeping the arms straight, lower the dumbbell in an arc behind your head until you feel a stretch in the lats.',
      'Pull the weight back over your chest using your lats, breathing out as you return to the start.'
    ],
    tips: ['Use a moderate load and controlled tempo', 'Avoid excessive bend in the elbows'],
    equipment: ['dumbbell', 'bench'],
    caloriesPerMinute: 6,
  }),
  ex({
    name: 'Rope Pullover',
    muscleGroup: { primary: 'back', secondary: ['lats', 'triceps'] },
    category: 'strength',
    difficulty: 'intermediate',
    description: 'Cable rope pullover that targets the lats with a controlled pulling motion.',
    instructions: [
      'Attach a rope to a high pulley and stand facing the machine.',
      'Grab the rope ends with a neutral grip and step back slightly, keeping a soft bend in your elbows.',
      'Pull the rope down and back in a sweeping arc until the hands reach your thighs.',
      'Slowly return to the start position with tension in the lats.',
    ],
    tips: ['Keep elbows from flaring out', 'Maintain a controlled eccentric'],
    equipment: ['cable machine', 'rope attachment'],
    caloriesPerMinute: 6,
  }),
];

// Real exercise demonstration images from the open-source yuhonas/free-exercise-db
// dataset, served via the GitHub raw CDN. Each slug maps to a verified directory id
// in that repo. Pattern: https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/{id}/0.jpg
const SLUG_TO_REPO_ID: Record<string, string> = {
  // chest
  'barbell-bench-press': 'Barbell_Bench_Press_-_Medium_Grip',
  'incline-dumbbell-press': 'Incline_Dumbbell_Press',
  'decline-barbell-press': 'Decline_Barbell_Bench_Press',
  'flat-dumbbell-press': 'Dumbbell_Bench_Press',
  'dumbbell-fly': 'Dumbbell_Flyes',
  'cable-crossover': 'Cable_Crossover',
  'push-up': 'Pushups',
  'diamond-push-up': 'Close-Grip_Push-Up_off_of_a_Dumbbell',
  'chest-dip': 'Dips_-_Chest_Version',
  // back
  'pull-up': 'Pullups',
  'chin-up': 'Chin-Up',
  'lat-pulldown': 'Wide-Grip_Lat_Pulldown',
  'bent-over-barbell-row': 'Bent_Over_Barbell_Row',
  't-bar-row': 'T-Bar_Row_with_Handle',
  'seated-cable-row': 'Seated_Cable_Rows',
  'single-arm-dumbbell-row': 'One-Arm_Dumbbell_Row',
  'conventional-deadlift': 'Barbell_Deadlift',
  'romanian-deadlift': 'Romanian_Deadlift',
  'face-pull': 'Face_Pull',
  'barbell-shrug': 'Barbell_Shrug',
  // shoulders
  'overhead-barbell-press': 'Barbell_Shoulder_Press',
  'seated-dumbbell-shoulder-press': 'Seated_Dumbbell_Press',
  'arnold-press': 'Arnold_Dumbbell_Press',
  'dumbbell-lateral-raise': 'Side_Lateral_Raise',
  'front-raise': 'Front_Dumbbell_Raise',
  'reverse-pec-deck': 'Reverse_Flyes',
  'barbell-upright-row': 'Upright_Barbell_Row',
  'push-press': 'Push_Press',
  // biceps
  'barbell-curl': 'Barbell_Curl',
  'dumbbell-curl': 'Dumbbell_Bicep_Curl',
  'hammer-curl': 'Hammer_Curls',
  'preacher-curl': 'Preacher_Curl',
  'cable-curl': 'Standing_Biceps_Cable_Curl',
  'concentration-curl': 'Concentration_Curls',
  'incline-dumbbell-curl': 'Incline_Dumbbell_Curl',
  // triceps
  'tricep-pushdown': 'Triceps_Pushdown',
  'skull-crusher': 'EZ-Bar_Skullcrusher',
  'overhead-tricep-extension': 'Triceps_Overhead_Extension_with_Rope',
  'close-grip-bench-press': 'Close-Grip_Barbell_Bench_Press',
  'tricep-dip': 'Dips_-_Triceps_Version',
  'rope-tricep-pushdown': 'Triceps_Pushdown_-_Rope_Attachment',
  // legs / quads / glutes / hamstrings
  'barbell-back-squat': 'Barbell_Squat',
  'front-squat': 'Front_Barbell_Squat',
  'goblet-squat': 'Goblet_Squat',
  'walking-lunge': 'Bodyweight_Walking_Lunge',
  'bulgarian-split-squat': 'Split_Squats',
  'leg-press': 'Leg_Press',
  'leg-curl': 'Lying_Leg_Curls',
  'leg-extension': 'Leg_Extensions',
  'standing-calf-raise': 'Standing_Calf_Raises',
  'hip-thrust': 'Barbell_Hip_Thrust',
  'sumo-deadlift': 'Sumo_Deadlift',
  'hack-squat': 'Hack_Squat',
  'step-up': 'Dumbbell_Step_Ups',
  // core
  'plank': 'Plank',
  'side-plank': 'Push_Up_to_Side_Plank',
  'crunch': 'Crunches',
  'russian-twist': 'Russian_Twist',
  'hanging-leg-raise': 'Hanging_Leg_Raise',
  'bicycle-crunch': 'Cross-Body_Crunch',
  'cable-crunch': 'Cable_Crunch',
  'dead-bug': 'Dead_Bug',
  'ab-wheel-rollout': 'Barbell_Ab_Rollout',
  // cardio
  'treadmill-run': 'Running_Treadmill',
  'stationary-bike': 'Bicycling_Stationary',
  'rowing-machine': 'Rowing_Stationary',
  'jump-rope': 'Rope_Jumping',
  'stair-climber': 'Stairmaster',
  'elliptical': 'Elliptical_Trainer',
  'mountain-climbers': 'Mountain_Climbers',
  'box-jump': 'Front_Box_Jump',
  'kettlebell-swing': 'One-Arm_Kettlebell_Swings',
  'battle-ropes': 'Battling_Ropes',
  'sled-push': 'Sled_Push',
  'barbell-thruster': 'Kettlebell_Thruster',
  // stretches
  'cat-cow-stretch': 'Cat_Stretch',
  'hip-flexor-stretch': 'Kneeling_Hip_Flexor',
  'standing-hamstring-stretch': 'Standing_Hamstring_and_Calf_Stretch',
  // home / no-gym
  'glute-bridge': 'Butt_Lift_Bridge',
  'wall-sit': 'Chair_Squat',
  'reverse-lunge': 'Bodyweight_Walking_Lunge',
  'pike-push-up': 'Pushups',
  'chair-dip': 'Bench_Dips',
  'backpack-goblet-squat': 'Goblet_Squat',
  'superman': 'Superman',
  'bird-dog': 'Glute_Kickback',
  // added mappings for new seeded exercises
  'reverse-wrist-curl': 'Wrist_Roller',
  'standing-cable-hip-adduction': 'Cable_Hip_Adduction',
  'standing-cable-hip-abduction': 'Cable_Hip_Abduction',
  'straight-arm-dumbbell-pullover': 'Straight_Arm_Dumbbell_Pullover',
  'rope-pullover': 'Straight_Arm_Dumbbell_Pullover',
};

// Anything not in the slug map (e.g. burpees, wall ball, pigeon stretch) falls
// back to a representative exercise from the same muscle group, so the card
// still shows a real demo image rather than a 404.
const MUSCLE_FALLBACK_ID: Record<string, string> = {
  chest:      'Dumbbell_Bench_Press',
  back:       'Bent_Over_Barbell_Row',
  shoulders:  'Barbell_Shoulder_Press',
  biceps:     'Barbell_Curl',
  triceps:    'Triceps_Pushdown',
  legs:       'Barbell_Squat',
  quads:      'Barbell_Squat',
  hamstrings: 'Romanian_Deadlift',
  glutes:     'Barbell_Hip_Thrust',
  core:       'Plank',
  cardio:     'Mountain_Climbers',
  flexibility: 'Cat_Stretch',
};

const GITHUB_EXERCISE_BASE =
  'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises';

function imageForExercise(slug: string, muscle: string | undefined): string {
  const repoId =
    SLUG_TO_REPO_ID[slug] ??
    MUSCLE_FALLBACK_ID[(muscle ?? '').toLowerCase()] ??
    'Barbell_Squat';
  return `${GITHUB_EXERCISE_BASE}/${repoId}/0.jpg`;
}

// MET value by Exercise.category. Bodyweight exercises get bumped up slightly
// inside the strength bucket, and running cardio gets a higher MET than cycling.
const CATEGORY_MET_DEFAULT: Record<string, number> = {
  strength: 5.0,
  HIIT: 8.0,
  cardio: 7.5,
  flexibility: 2.5,
};

function metForSeed(e: SeedExercise): number {
  const equip = e.equipment.map((x) => x.toLowerCase());
  const isBodyweight = equip.length === 0 || equip.every((x) => x === 'mat' || x === 'bodyweight');
  if (e.category === 'cardio') {
    if (/run|treadmill|sprint|jump|burpee|mountain/i.test(e.name)) return 9.8;
    if (/bike|cycl|ellipt|row|stair/i.test(e.name)) return 7.5;
    return 7.0;
  }
  if (e.category === 'HIIT') return 8.0;
  if (e.category === 'flexibility') return 2.5;
  if (e.category === 'strength' && isBodyweight) return 4.0;
  return CATEGORY_MET_DEFAULT[e.category] ?? 4.5;
}

// Gear you can reasonably have at home (or improvise) — used to flag exercises
// as doable without a gym. Anything needing a barbell, machine, bench, cable,
// rack, etc. is treated as gym-only.
const HOME_EQUIPMENT = new Set([
  'bodyweight',
  'mat',
  'wall',
  'chair',
  'backpack',
  'jump rope',
]);

function locationForSeed(e: SeedExercise): 'home' | 'gym' {
  if (e.equipment.length === 0) return 'home';
  return e.equipment.every((x) => HOME_EQUIPMENT.has(x.toLowerCase())) ? 'home' : 'gym';
}

export function withDerivedFields(e: SeedExercise) {
  const slug = slugify(e.name);
  const imageUrl = imageForExercise(slug, e.muscleGroup.primary);
  const videoUrl = `https://www.youtube.com/results?search_query=${encodeURIComponent(
    e.name + ' exercise tutorial'
  )}`;
  const metValue = metForSeed(e);
  const location = locationForSeed(e);
  return { ...e, slug, imageUrl, videoUrl, metValue, location };
}

export interface SeedTemplate {
  name: string;
  description: string;
  exerciseNames: string[];
}

export const seedTemplates: SeedTemplate[] = [
  {
    name: 'Push Day',
    description: 'Chest, shoulders, and triceps.',
    exerciseNames: [
      'Barbell Bench Press',
      'Incline Dumbbell Press',
      'Overhead Barbell Press',
      'Dumbbell Lateral Raise',
      'Tricep Pushdown',
      'Cable Crossover',
    ],
  },
  {
    name: 'Pull Day',
    description: 'Back and biceps.',
    exerciseNames: [
      'Pull-Up',
      'Bent Over Barbell Row',
      'Lat Pulldown',
      'Face Pull',
      'Barbell Curl',
      'Hammer Curl',
    ],
  },
  {
    name: 'Leg Day',
    description: 'Lower-body strength.',
    exerciseNames: [
      'Barbell Back Squat',
      'Romanian Deadlift',
      'Bulgarian Split Squat',
      'Leg Curl',
      'Standing Calf Raise',
      'Hip Thrust',
    ],
  },
  {
    name: 'Upper Body',
    description: 'Full upper-body session.',
    exerciseNames: [
      'Barbell Bench Press',
      'Pull-Up',
      'Seated Dumbbell Shoulder Press',
      'Seated Cable Row',
      'Dumbbell Curl',
      'Skull Crusher',
    ],
  },
  {
    name: 'Full Body',
    description: 'Compound-focused total body workout.',
    exerciseNames: [
      'Barbell Back Squat',
      'Barbell Bench Press',
      'Bent Over Barbell Row',
      'Overhead Barbell Press',
      'Plank',
    ],
  },
];
